<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php echo APP_NAME  ?></title>
        <link rel="stylesheet" href="assets/css/style.css">
    </head>

    <body>
<div class="container">
	<img src="put any picture you desire, something cute, etc.">
</div>
        <b><p>
		//you can put info here, like twitter, etc.
	<a href=""></a>
	<p>
	<a href=""></a>
    </body>
</html>	