<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php echo APP_NAME . " - $file.$stype"; ?></title>
        <link rel="stylesheet" href="/assets/css/style.css">
<?php if (TWITTER_CARDS) { ?>
        <meta name="twitter:card" content="photo" />
        <meta name="twitter:site" content="<?php echo TWITTER_HANDLE; ?>" />
        <meta name="twitter:title" content="<?php echo $file . '.' . $stype; ?>" />
        <meta name="twitter:image" content="http://<?php echo $_SERVER['SERVER_NAME']; ?><?php echo IMAGESERVE_DIR; ?>/images/<?php echo "$type/$file.$stype"; ?>" />
        <meta name="twitter:url" content="http://<?php echo $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI']; ?>" />
<?php } ?>
    </head>

    <body>

        <div class="container">
            <?php if ($stype == mp4): ?>
                <video controls autoplay width="1280" height="720" >
                     <source src="/images/mp4" type="video/mp4">
                </video>
             <?php else if ($stype == webm): ?>
                <video controls autoplay width="1280" height="720" >
                     <source src="/images/webm>" type="video/webm">
                </video>
            <?php else ?>
                <img src="images/<?php echo "$type/$file.$stype"; ?>" alt="<?php echo "$file.$stype"; ?>">
            <?php endif; ?>
        </div>

        <p>
        <a href="http://twitter.com/coolguyquietess>twitter</a>
        </p>
    </body>
</html>
